spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  h2:
    console:
      enabled: false
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

logging:
  level:
    org.springframework.security: WARN
    org.hibernate.SQL: WARN

config:
  security:
    jwt:
      secret: ${JWT_SECRET}
    cors:
      allowed-origins: ${CORS_ALLOWED_ORIGINS}
  pagination:
    base-url: ${API_BASE_URL}
  bootstrap:
    seed-enabled: false
